language: csharp
mono: none
dotnet: 3.1

deploy:
- provider: script
  script:
  - dotnet restore
  - dotnet build --no-restore -c Release
  on:
    branch: master
   
- provider: script
  script:
  - dotnet restore
  - dotnet build --no-restore -c Release /p:Version=$TRAVIS_TAG
  - dotnet nuget push "**.nupkg" -k $NUGET_APIKEY
  on:
    tags: true