language: csharp
mono: none
dotnet: 3.1

install: dotnet restore
script:
- |
  if [[ "$TRAVIS_TAG" =~ "^\d+(\.\d+){1,3}$" ]]; then
    export VERSION="$TRAVIS_TAG"
  else 
    export VERSION="0.0.1"
  fi
  dotnet build --no-restore -c Release /p:Version=$VERSION

deploy:
- provider: script
  script:
  - dotnet nuget push "**.nupkg" -k $NUGET_APIKEY
  on:
    tags: true