language: csharp
mono: none
dotnet: 3.1

install: dotnet restore
script:
- echo TRAVIS_TAG=$TRAVIS_TAG
- |
  if [[ "$TRAVIS_TAG" =~ ^[0-9]+(\.[0-9]+){1,3}$ ]]; then
    export VERSION="$TRAVIS_TAG"
  else 
    export VERSION="0.0.1"
  fi
- VERSION=$VERSION
- dotnet build --no-restore -c Release /p:Version=$VERSION

deploy:
- provider: script
  skip_cleanup: true
  script: dotnet nuget push "**.nupkg" -s nuget.org -k $NUGET_APIKEY
  on:
    tags: true